version: '2'
services:
  server:
    image: server
    restart: always
    ports:
    - "8000:8000"

  client:
    image: client
    stdin_open: true
    depends_on:
      - server
    links:
      - server
    ports:
    - "8001:8001"
